CREATE TABLE people(
PeopleId INT PRIMARY KEY,
FirstName NVARCHAR (20) NOT NULL,
Surname NVARCHAR (20) NOT NULL,
Email NVARCHAR (40) NOT NULL,
);

CREATE TABLE Events(
EventId INT PRIMARY KEY,
Name NVARCHAR (30) NOT NULL,
Organiser NVARCHAR (30) NOT NULL,
Location NVARCHAR (40) NOT NULL,
Description NVARCHAR (255) NOT NULL,
TeamBased BOOLEAN NOT NULL,
DReq BOOLEAN NOT NULL,
FOREIGNKEY (PeopleId) REFERENCES People(PeopleId)
);
